DJANGO_COURSE_1.xx/Django_Level_Four/learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# SET THE NAMESPACE!
app_name = 'basic_app'

urlpatterns=[
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
]

DJANGO_COURSE_1.xx/Django_Level_Four/learning_templates/learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls'))
]

DJANGO_COURSE_1.xx/Django_Level_Four/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

DJANGO_COURSE_1.xx/Django_Level_Four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

DJANGO_COURSE_1.xx/Django_Level_Four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">



    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>


  </body>
</html>

DJANGO_COURSE_1.xx/Django_Level_Four/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block%}

    <h1>Hello and welcome to the site!</h1>
    <h1>This is the index.html page</h1>

    {% endblock %}

DJANGO_COURSE_1.xx/Django_Level_Four/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>This is an example of template inheritance!</h1>
    <h2>Officially this is the other.html page!</h2>
    {% endblock %}

DJANGO_COURSE_1.xx/Django_Level_Four/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Relative Urls</title>
  </head>
  <body>
    <h1>Welcome!</h1>
    <p>
      This page serves as an example of how to
      use relative urls with templates!
      This is the relative_url_templates.html file.
    </p>

    {# Here are the examples:#}
    {# Must set the app_name=basic_app variable inside the basic_app/urls.py#}
    <a href="{% url 'admin:index' %}">Link to Admin Page</a>

    <a href="{% url 'basic_app:other' %}">Link to other.html</a>


  </body>
</html>