DJANGO_COURSE_1.xx/Advanced_Django_CBV/advcbv/advcbv/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'^$',views.IndexView.as_view()),
    url(r'^basic_app/',include('basic_app.urls',namespace='basic_app')),
    # url(r'^$',views.CBView.as_view()),
    # url(r'^$',views.index)
]

DJANGO_COURSE_1.xx/Advanced_Django_CBV/advcbv/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete')
]

DJANGO_COURSE_1.xx/Advanced_Django_CBV/advcbv/basic_app/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students')

    def __str__(self):
        return self.name

DJANGO_COURSE_1.xx/Advanced_Django_CBV/advcbv/basic_app/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)
from . import models
# Create your views here.

# Original Function View:
#
# def index(request):
#     return render(request,'index.html')
#
#

# Pretty simple right?
class IndexView(TemplateView):
    # Just set this Class Object Attribute to the template page.
    # template_name = 'app_name/site.html'
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context  = super().get_context_data(**kwargs)
        context['injectme'] = "Basic Injection!"
        return context

class SchoolListView(ListView):
    # If you don't pass in this attribute,
    # Django will auto create a context name
    # for you with object_list!
    # Default would be 'school_list'

    # Example of making your own:
    # context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_details'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ("name","principal","location")
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ("name","principal")
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")


class CBView(View):
    def get(self,request):
        return HttpResponse('Class Based Views are Cool!')

DJANGO_COURSE_1.xx/Advanced_Django_CBV/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      CBVs
      {# Title Extensions go inside the block#}
      {% block title_block %}

      {% endblock %}
    </title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:create' %}">Create School</a></li>
        </ul>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}


  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-3.2.0.min.js"
  integrity="sha256-JAW99MJVpJBGcbzEuXk4Az05s/XyDdBomFqNlM3ic+I="
  crossorigin="anonymous"></script>
</html>

DJANGO_COURSE_1.xx/Advanced_Django_CBV/advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<h1>Delete {{school.name }}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'basic_app:detail' pk=school.pk%} ">Cancel</a>

</form>

{% endblock %}

DJANGO_COURSE_1.xx/Advanced_Django_CBV/advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School Details:</h2>
    <p>Id_num: {{school_details.id}}</p>
    <p>Name: {{school_details.name}}</p>
    <p>Principal: {{school_details.principal}}</p>
    <p>Location: {{school_details.location}}</p>
    <h3>Students:</h3>

      {% for student in school_details.students.all %}
        <p>{{student.name}} who is {{student.age}} years old.</p>
      {% endfor %}

  </div>
  <div class="container">
    <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_details.pk %}">Update</a></p>

  </div>

{% endblock %}

DJANGO_COURSE_1.xx/Advanced_Django_CBV/advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>


{% endblock %}

DJANGO_COURSE_1.xx/Advanced_Django_CBV/advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
  <div class="jumbotron">

    <h1>Welcome to the List of Schools Page!</h1>
      <ol>
        {% for school in school_list %}
          <h2><li><a href="{{school.id}}/">{{school.name}} </a></li></h2>
        {% endfor %}
      </ol>

  </div>


{% endblock %}